export const providerCopy = {
  en: {
    title: "Providers",
    description: "Configuration schema v2",
    setupTitle: "Configure your first provider",
    setupDescription:
      "Gateway setup is waiting for a provider, model, and key.",
    setupAdd: "Add first provider",
    add: "Add provider",
    empty: "No providers configured",
    emptyDescription: "The provider list is empty.",
    enabled: "Enabled",
    disabled: "Disabled",
    default: "Default",
    models: "Models",
    keys: "Keys",
    alias: "Codex alias",
    upstream: "Upstream model",
    weight: "Weight",
    keyEnabled: "Key enabled",
    alwaysTry: "Always try",
    alwaysTryDescription:
      "Keep this key eligible after authentication or upstream failures.",
    fingerprint: "Fingerprint",
    edit: "Edit provider",
    test: "Test connection",
    remove: "Delete provider",
    setDefault: "Set as default",
    setDefaultModel: "Set default model",
    addTitle: "Add provider",
    editTitle: "Edit provider",
    formDescription: "Provider configuration schema v2",
    advancedSettings: "Advanced settings",
    providerId: "Provider ID",
    providerIdHint: "Lowercase letters, numbers, and hyphens.",
    name: "Display name",
    baseUrl: "Base URL",
    upstreamFormat: "Upstream API format",
    apiProfile: "API profile",
    apiProfileDescription:
      "Select provider-specific Responses capabilities and defaults.",
    genericApiProfile: "Generic",
    deepSeekApiProfile: "DeepSeek",
    responsesFormat: "Responses",
    chatCompletionsFormat: "Chat Completions",
    encryptedAgentMessages: "Native agent messages",
    encryptedAgentMessagesDescription:
      "Pass MultiAgentV2 agent_message items to the Responses upstream unchanged.",
    encryptedAgentMessagesUnavailable:
      "Native agent messages require a Responses upstream.",
    promptCacheKey: "Forward prompt cache key",
    promptCacheKeyDescription:
      "Forward Responses prompt_cache_key to this Chat Completions upstream.",
    promptCacheKeyUnavailable:
      "Prompt cache keys apply only to Chat Completions upstreams.",
    modelId: "Model ID",
    modelName: "Model name",
    upstreamModel: "Upstream model",
    imageInput: "Image input",
    textOnly: "Text only",
    hostedWebSearch: "Hosted Web Search",
    hostedWebSearchDescription:
      "Allow Codex to send the Responses web_search hosted tool.",
    hostedWebSearchUnavailable:
      "Hosted Web Search requires a Responses upstream.",
    customApplyPatch: "Custom apply_patch",
    customApplyPatchDescription:
      "Allow Codex to send the Responses custom apply_patch tool.",
    customApplyPatchUnavailable:
      "Custom apply_patch requires a Responses upstream.",
    reasoning: "Reasoning effort",
    reasoningDescription:
      "Expose model-supported thinking levels to Codex and map them upstream.",
    reasoningLevels: "Available levels",
    reasoningParameter: "Chat parameter",
    reasoningValues: "Upstream values",
    reasoningValuesDescription:
      "Optional comma-separated values matching the levels; useful for budgets or boolean switches.",
    reasoningDefault: "Default level",
    keyName: "Key name",
    apiKey: "API key",
    keepKey: "Leave blank to keep the current key.",
    addModel: "Add model",
    fetchModels: "Fetch models",
    modelsFound: (count: number) => `${count} upstream models found`,
    addFetchedModel: "Add",
    modelAdded: "Added",
    noModelsFound: "The upstream returned no models.",
    addKey: "Add key",
    balanceQuery: "Balance query",
    balanceEnabled: "Balance query enabled",
    balanceDisabled: "Balance query disabled",
    balanceCode: "JavaScript",
    balanceTimeout: "Timeout (ms)",
    balanceRefresh: "Refresh override (ms)",
    deepSeekTemplate: "DeepSeek template",
    openRouterTemplate: "OpenRouter template",
    testBalance: "Test balance query",
    balanceTested: (value: string) => `Balance query succeeded · ${value}`,
    cancel: "Cancel",
    discardChanges: "Discard unsaved provider changes?",
    concurrentChange:
      "Provider configuration changed after this editor was opened. Close and reopen the editor before saving.",
    reenterKeysForOrigin:
      "Re-enter every existing API key before changing the provider origin.",
    reenterKey: "This key must be re-entered for the new provider origin.",
    save: "Save provider",
    create: "Create provider",
    deleteTitle: "Delete provider?",
    deleteDescription:
      "This removes the provider, its model aliases, and its key pool.",
    delete: "Delete",
    connected: "Connection succeeded",
    failed: "Request failed",
  },
  "zh-CN": {
    title: "Provider 管理",
    description: "配置结构 v2",
    setupTitle: "配置首个 Provider",
    setupDescription: "Gateway 正在等待 Provider、模型和密钥配置。",
    setupAdd: "添加首个 Provider",
    add: "添加 Provider",
    empty: "尚未配置 Provider",
    emptyDescription: "Provider 列表为空。",
    enabled: "已启用",
    disabled: "已停用",
    default: "默认",
    models: "模型",
    keys: "密钥",
    alias: "Codex 别名",
    upstream: "上游模型",
    weight: "权重",
    keyEnabled: "启用密钥",
    alwaysTry: "始终尝试",
    alwaysTryDescription: "鉴权或上游失败后，后续请求仍可继续使用此密钥。",
    fingerprint: "指纹",
    edit: "编辑 Provider",
    test: "测试连接",
    remove: "删除 Provider",
    setDefault: "设为默认",
    setDefaultModel: "设为默认模型",
    addTitle: "添加 Provider",
    editTitle: "编辑 Provider",
    formDescription: "Provider 配置结构 v2",
    advancedSettings: "高级设置",
    providerId: "Provider ID",
    providerIdHint: "仅使用小写字母、数字和连字符。",
    name: "显示名称",
    baseUrl: "Base URL",
    upstreamFormat: "上游 API 格式",
    apiProfile: "API Profile",
    apiProfileDescription: "选择 Provider 专用的 Responses 能力和默认值。",
    genericApiProfile: "通用",
    deepSeekApiProfile: "DeepSeek",
    responsesFormat: "Responses",
    chatCompletionsFormat: "Chat Completions",
    encryptedAgentMessages: "原生代理消息透传",
    encryptedAgentMessagesDescription:
      "将 MultiAgentV2 agent_message 项不经兼容转换直接发送给 Responses 上游。",
    encryptedAgentMessagesUnavailable:
      "原生代理消息透传要求上游使用 Responses 协议。",
    promptCacheKey: "转发 prompt cache key",
    promptCacheKeyDescription:
      "将 Responses 的 prompt_cache_key 转发给此 Chat Completions 上游。",
    promptCacheKeyUnavailable:
      "prompt cache key 仅适用于 Chat Completions 上游。",
    modelId: "模型 ID",
    modelName: "模型名称",
    upstreamModel: "上游模型",
    imageInput: "图像输入",
    textOnly: "仅文本",
    hostedWebSearch: "托管网页搜索",
    hostedWebSearchDescription:
      "允许 Codex 发送 Responses web_search 托管工具。",
    hostedWebSearchUnavailable: "托管网页搜索要求上游使用 Responses 协议。",
    customApplyPatch: "自定义 apply_patch",
    customApplyPatchDescription:
      "允许 Codex 发送 Responses custom apply_patch 工具。",
    customApplyPatchUnavailable:
      "自定义 apply_patch 要求上游使用 Responses 协议。",
    reasoning: "思考强度",
    reasoningDescription:
      "向 Codex 声明模型支持的思考级别，并映射到上游参数。",
    reasoningLevels: "可用级别",
    reasoningParameter: "Chat 参数",
    reasoningValues: "上游取值",
    reasoningValuesDescription:
      "可选，按级别顺序填写上游值，适用于预算或布尔开关参数。",
    reasoningDefault: "默认级别",
    keyName: "密钥名称",
    apiKey: "API 密钥",
    keepKey: "留空可保留当前密钥。",
    addModel: "添加模型",
    fetchModels: "获取模型",
    modelsFound: (count: number) => `已获取 ${count} 个上游模型`,
    addFetchedModel: "添加",
    modelAdded: "已添加",
    noModelsFound: "上游没有返回模型。",
    addKey: "添加密钥",
    balanceQuery: "额度查询",
    balanceEnabled: "已启用额度查询",
    balanceDisabled: "已停用额度查询",
    balanceCode: "JavaScript",
    balanceTimeout: "超时（毫秒）",
    balanceRefresh: "覆盖刷新周期（毫秒）",
    deepSeekTemplate: "DeepSeek 模板",
    openRouterTemplate: "OpenRouter 模板",
    testBalance: "测试额度查询",
    balanceTested: (value: string) => `额度查询成功 · ${value}`,
    cancel: "取消",
    discardChanges: "放弃尚未保存的 Provider 修改？",
    concurrentChange:
      "打开编辑器后 Provider 配置已发生变化。请关闭并重新打开编辑器后再保存。",
    reenterKeysForOrigin: "更改 Provider 来源前，请重新输入所有现有 API 密钥。",
    reenterKey: "新的 Provider 来源要求重新输入此密钥。",
    save: "保存 Provider",
    create: "创建 Provider",
    deleteTitle: "删除 Provider？",
    deleteDescription: "Provider、模型别名及其独立密钥池都会被移除。",
    delete: "删除",
    connected: "连接成功",
    failed: "请求失败",
  },
} as const

export type ProviderCopy = (typeof providerCopy)[keyof typeof providerCopy]
